### ISSUE TITLE
Thinner resolution in online coaching crops the picture so the head doesn't show. 768px screen.

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#27]

**Comment by michalchemo** [comment]
done

**Comment by gur111** [comment]
I still have problems with it. This is after refresh:
![image](https://user-images.githubusercontent.com/7829415/34360281-bc63ebea-ea67-11e7-98a5-0af642859296.png)
My PC resolution is under 1080p height.

**Comment by deldnm012** [comment]
Done

**Comment by gur111** [comment]
Gr8
