### ISSUE TITLE
Can't create new user under free package

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#38]
The password always indicates as invalid without giving a reason.
After I bypassed that using local workaround it gives a blank thank you page (only the title says thanks you, the page contains nothing)

**Comment by michalchemo** [comment]
Done
thank you page message you can manage from package( admin side ) here : 
http://authedge.co.il/wp-admin/post.php?post=766&action=edit

**Comment by gur111** [comment]
I don't see the issue resolved. I still can't register as new user (for free trial).
I am not trying to create the user as admin but as a visitor: http://authedge.co.il/register/free-package/

**Comment by deldnm012** [comment]
Done, Please Check
