### ISSUE TITLE
Zooming changes the נעץ's location

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#6]

**Comment by michalchemo** [comment]
done - up to 1200px screen

**Comment by gur111** [comment]
Still exists. Only not all the נעצים I added yesterday moved down by about 100px.

**Comment by michalchemo** [comment]
Havent we finished this one? :?

**Comment by gur111** [comment]
We did
