### ISSUE TITLE
The age of a notification is for some reason 12 hours ahead.

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#62]
For some reason right after creating a notification it will already show that it existed 12 hours already.
Also the phrasing should be according to the actual time.
It should show: 

> יום, 3 שעות, 13 דקות 

and not 
> 1 יום, 11 שעה, 12 דקה
(The 1 should be on the other side. Mixing Hebrew and English in this isn't great, here's an image though the numbers are a bit different there because I took another notification as an example)
![image](https://user-images.githubusercontent.com/7829415/34386766-fa200506-eb32-11e7-8260-92800a1eda61.png)

**Comment by deldnm012** [comment]
Done

**Comment by gur111** [comment]
Ok. So the age was corrected. Thanks.
Now the format should be as followed
Minute - דקה
Minutes - דקות
Hour - שעה
Hours - שעות
Day - יום
Days - ימים

**Comment by deldnm012** [comment]
Done

**Comment by gur111** [comment]
The notification still shows the singular form when there are more than one minute. In Hebrew it means 2 minute and it should show minutes when it's more than one.

**Comment by deldnm012** [comment]
Please Check this : http://prntscr.com/hupvfq

**Comment by gur111** [comment]
Can you only make that the numbers don't show when in singular form? So instead of "לפני 1 יום" it will be "לפני יום"?

**Comment by deldnm012** [comment]
No that's not possible

**Comment by gur111** [comment]
Ohh well. So it's closed then
