### ISSUE TITLE
Time left until a notification needs to be replied isn't calculated correctly. I always see 15 דקות instead of the actual number.

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#63]

**Comment by deldnm012** [comment]
right click on document and click on הצג הערה you can see list of annotation and left times

**Comment by gur111** [comment]
Actually I meant that part:
![image](https://user-images.githubusercontent.com/7829415/34439264-456e84d2-ecb5-11e7-9b4b-bb371f8573c9.png)
It always shows 15 minutes. Since I wrote that issue it didn't change.
Also, the "הצג הערות" isn't useful at all but I will have to clear this specific point with Michal when she comes back. Because students don't have that option in the menu so they don't see the times left on their document and mentors don't have the student's document to right click on and on their document no one posts comments so it will always be empty. Anyways, the thing I show in the picture should be corrected though.

**Comment by michalchemo** [comment]
הצג סימניות

**Comment by deldnm012** [comment]
Done http://prntscr.com/hvgis5

**Comment by gur111** [comment]
This is still wrong. After a minute or two or even 10 hours the time stays the same. 
The time left should be the time until the mentor needs to respond depending on the user's subscription. It's basically a response timer. If the subscriptions states 2 days response then the mentor will see right when the users creates a comment 48 hours. After an hour it should show 47 hours and so on...

**Comment by michalchemo** [comment]
גור - זוהי חבילה של הלקוח
יש סוג חבילה, ומציגים פה רק את זמן התגובה המקורי שלה.
זמן תגובה מחושב לפי THRED
וזה באזור אחר של היוזר - אזור ההערות, לא פה..

**Comment by gur111** [comment]
I don't think I understand where I see the actual time left until the mentor needs to respond. Also I don't understand what this value is if not that.

**Comment by michalchemo** [comment]
http://prntscr.com/hxjxzm
http://prntscr.com/hxjy43

זה לדעתי פותר את הנושא

**Comment by gur111** [comment]
I consider this one closed. Though there is a small issue. When mentor goes to מסמכי עבודה then chooses student and go to הצג הערות the time is in English. Minutes and not דקות etc...
![image](https://user-images.githubusercontent.com/7829415/34683820-e177d448-f4ab-11e7-820b-63a91fb56137.png)
